### ISSUE TITLE
Newlines are interpreted literally.

### ISSUE THREAD

**Issue by lexisother** [Cumcord/sperm#1]
## Description of issue
Sperm interprets the newline escape character (`\n`) literally and thus produces an actual newline in the built plugin.

## Info
Input plugin:
```js
export default {
  onLoad(){
    console.log("\n")
  },
  onUnload(){

  }
}
```

Output plugin:
```js
(function(){"use strict";var n={onLoad(){console.log(`
`)},onUnload(){}};return n})();
```

Sperm version:
```
└─$ sperm --version
0.0.31
```

**Comment by Cr3atable** [comment]
This is just minification.
